PUT http://localhost:8080/logs/init-log
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpcCI6IjAuMC4wLjAiLCJjcmVhdGlvbiI6MTY4MDkzMzY1MTEyNCwiZXhwaXJlcyI6bnVsbCwidXNlcm5hbWUiOiJkbWVvIG1hbnRyYSIsImVtYWlsIjoiZ29oaWxtYW50cmFAZ21haWwuY29tIiwiaWF0IjoxNjgwOTMzNjUxfQ.CE4M8ueWT54w-Uf0CEhMTJD0NKLhXy8sqGO3a4ooF1c
token: 51ee93d3-e169-445d-870b-1c88d37b75aa