GET /dev/bulkV2?authorization=NcPueB7DZ2fqFXHl0obiOQAt9asJSk3pxC4rvYIUhWGjzTy61gbD1l4xz2iykFSJBgQcrXT3puNvCeH6&route=otp&variables_values=4433&flash=1&numbers=6354049067 HTTP/1.1
Host: www.fast2sms.com
